config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	registrations: 'users/registrations'
  }
  root to: 'joboffers#index'
  get 'users/show'

  resources :joboffers
  resources :joboffers, only: :show do
  	resources :agreements, only: :create
  end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


# Rails.application.routes.draw do
#   get 'users/show'
#   resources :joboffers
#   root to: 'joboffers#index'
#   devise_for :users
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

app/models/joboffer.rb
class Joboffer < ApplicationRecord
  belongs_to :user
  has_one :conversation
  belongs_to :location
  belongs_to :skill

  has_one :agreement
  belongs_to :user
  has_many :comment
end

app/controllers/joboffers_controller.rb
class JoboffersController < ApplicationController
  #before_action :set_joboffer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :show]
  load_and_authorize_resource
  # GET /joboffers
  # GET /joboffers.json
  def index
    @joboffers = Joboffer.all.order('created_at DESC')
  end

  # GET /joboffers/1
  # GET /joboffers/1.json
  def show
  end

  # GET /joboffers/new
  def new
    @joboffer = Joboffer.new
  end

  # GET /joboffers/1/edit
  def edit
  end

  def agreement
  end

  # POST /joboffers
  # POST /joboffers.json
  def create
    @joboffer = Joboffer.new(joboffer_params)
    @joboffer.user = current_user
    respond_to do |format|
      if @joboffer.save
        format.html { redirect_to @joboffer, notice: 'Joboffer was successfully created.' }
        format.json { render :show, status: :created, location: @joboffer }
      else
        format.html { render :new }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joboffers/1
  # PATCH/PUT /joboffers/1.json
  def update
    respond_to do |format|
      if @joboffer.update(joboffer_params)
        format.html { redirect_to @joboffer, notice: 'Joboffer was successfully updated.' }
        format.json { render :show, status: :ok, location: @joboffer }
      else
        format.html { render :edit }
        format.json { render json: @joboffer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joboffers/1
  # DELETE /joboffers/1.json
  def destroy
    @joboffer.destroy
    respond_to do |format|
      format.html { redirect_to joboffers_url, notice: 'Joboffer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joboffer
      @joboffer = Joboffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joboffer_params
      params.require(:joboffer).permit(:title, :description, :photo, :budget, :location_id, :skill_id, :start_date, :end_date, :user_id)
    end
end

app/helpers/joboffers_helper.rb
module JoboffersHelper
end

app/views/joboffers/_form.html.erb
<%= form_with(model: joboffer, local: true) do |form| %>
  <% if joboffer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joboffer.errors.count, "error") %> prohibited this joboffer from being saved:</h2>

      <ul>
      <% joboffer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="field">
    <%= form.label :budget %>
    <%= form.number_field :budget %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id %>
  </div>

  <div class="field">
    <%= form.label :skill_id %>
    <%= form.number_field :skill_id %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= current_user.name %>
    <%= current_user.last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/joboffers/edit.html.erb
<h1>Editing Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Show', @joboffer %> |
<%= link_to 'Back', joboffers_path %>

app/views/joboffers/index.html.erb
<div class="container-fluid">
    <%= render 'layouts/navbar' %>
    <%= link_to "Nuevo Aviso", new_joboffer_path, class:'btn btn-warning' %>
    <div class="row">
      <% @joboffers.each_slice(3) do |row| %>
        <% row.each do |joboffer| %>
          <div class="col">
            <div style="margin: 10px" class="card border bg-light">  
              <div style="padding: 10px" class="body">
                <tr>
                      <td><%= image_tag joboffer.photo,size:'400x200', class: "card-img-top" %></td>
                      <td><h5><%= joboffer.title %></h5></td>
                      <td><%= joboffer.description %></td>
                      <td><%= joboffer.location_id %></td>
                      <td><%= joboffer.user_id %></td>
                      <td><%= link_to "Mostrar", joboffer_path(joboffer), class:'btn btn-success' %></td>
                      <td>
                        <% if can?(:edit, joboffer) %>
                        <%= link_to 'Editar', edit_joboffer_path(joboffer), class: 'btn btn-info' %>
                        <% end %>
                      </td>
                      <td>
                        <% if can?(:destroy, joboffer) %>
                        <%= link_to 'Eliminar', joboffer, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
                          <% end %>
                      </td>
                    </tr>
                
              </div>
            </div>
          </div>
        <% end %>
        <div class="w-100"> </div>
      <% end %>
    </div>

    <%= link_to "Nuevo Aviso", new_joboffer_path, class:'btn btn-warning' %>

app/views/joboffers/new.html.erb
<h1>New Joboffer</h1>

<%= render 'form', joboffer: @joboffer %>

<%= link_to 'Back', joboffers_path %>

app/views/joboffers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @joboffer.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @joboffer.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @joboffer.photo %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @joboffer.budget %>
</p>

<p>
  <strong>Location:</strong>
  <%= @joboffer.location_id %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @joboffer.skill_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @joboffer.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @joboffer.end_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @joboffer.user.name %>
  <%= @joboffer.user.last_name %>
</p>

<%= link_to 'Edit', edit_joboffer_path(@joboffer) %> |
<%= link_to 'Back', joboffers_path %>